"""add_generation_counters

Revision ID: 13ec0d4a9aed
Revises: 20260425_182347
Create Date: 2026-04-28 00:37:56.423894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ec0d4a9aed'
down_revision: Union[str, Sequence[str], None] = '20260425_182347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generation_counters',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_system_alerts_id'), 'system_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_weather_forecast_days_id'), 'weather_forecast_days', ['id'], unique=False)
    op.create_index(op.f('ix_weather_readings_id'), 'weather_readings', ['id'], unique=False)
    op.create_index(op.f('ix_weather_warnings_id'), 'weather_warnings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_warnings_id'), table_name='weather_warnings')
    op.drop_index(op.f('ix_weather_readings_id'), table_name='weather_readings')
    op.drop_index(op.f('ix_weather_forecast_days_id'), table_name='weather_forecast_days')
    op.drop_index(op.f('ix_system_alerts_id'), table_name='system_alerts')
    op.drop_table('generation_counters')
    # ### end Alembic commands ###
