"""add_hne_columns

Revision ID: 3c51a1f1df57
Revises: 13ec0d4a9aed
Create Date: 2026-04-28 17:55:01.317205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c51a1f1df57'
down_revision: Union[str, Sequence[str], None] = '13ec0d4a9aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_readings', sa.Column('hne', sa.Float(), nullable=True))
    op.add_column('weather_readings', sa.Column('nightly_hne', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_readings', 'nightly_hne')
    op.drop_column('weather_readings', 'hne')
    # ### end Alembic commands ###
