"""Initial migration

Revision ID: e93db34a6dca
Revises: 
Create Date: 2026-02-07 23:44:35.058586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93db34a6dca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('total_contributions_count', sa.Integer(), nullable=True),
    sa.Column('total_financial_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('first_donation_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('last_donation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('communication_opt_in', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_profiles_email'), 'donor_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_donor_profiles_id'), 'donor_profiles', ['id'], unique=False)
    op.create_table('donation_pledges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('donor_name', sa.String(), nullable=False),
    sa.Column('donor_email', sa.String(), nullable=False),
    sa.Column('donor_phone', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('donation_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_estimated_value', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['donor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_pledges_id'), 'donation_pledges', ['id'], unique=False)
    op.create_table('donation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pledge_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_method', sa.String(), nullable=True),
    sa.Column('is_received', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pledge_id'], ['donation_pledges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_items_id'), 'donation_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_items_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_donation_pledges_id'), table_name='donation_pledges')
    op.drop_table('donation_pledges')
    op.drop_index(op.f('ix_donor_profiles_id'), table_name='donor_profiles')
    op.drop_index(op.f('ix_donor_profiles_email'), table_name='donor_profiles')
    op.drop_table('donor_profiles')
    # ### end Alembic commands ###
